### ISSUE TITLE
obsolete?

### ISSUE THREAD

**Issue by mc007** [csnover/dojo-boilerplate#62]
hi, Dylan mentioned that this template might be obsolete? Can you confirm that? I am interested to go on with this template. Thank you!

**Comment by csnover** [comment]
It is not obsolete.

/cc @dylans

**Comment by dylans** [comment]
I simply said that I thought https://github.com/bryanforbes/generator-dojo/ might be more useful than dojo-boilerplate for a new user, given that it also includes Intern as an option in the generator process. Clearly dojo-boilerplate has been updated for 1.10 so it's not obsolete.

**Comment by mc007** [comment]
jeez, ok then. i will make a fork of this here then for adding the same, our users felt quit overwhelmed with the yo-generator.  thanks Dylan.
