### ISSUE TITLE
build runs but throws error on run "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by JoshZen** [csnover/dojo-boilerplate#63]
trying to run dist/index.html  after the build fails with the error 
"Uncaught ReferenceError: require is not defined"
on 
require(['app/main']);

node- v0.10.28
java 1.8

**Comment by csnover** [comment]
There’s no `app/maintest` module, the boilerplate doesn’t come with that. Looks like you probably typed the word “test” into your code editor and then saved it?

**Comment by JoshZen** [comment]
Yes thats true because I was experimenting with renaming the output file, which works. So upon running a build on a clean branch I still get the same error.

**Comment by csnover** [comment]
OK, well, the only way `require` would be undefined is if `<script src="dojo/dojo.js">` was removed from the HTML or if you set `boot: false` on the `dojo/dojo` layer in your build profile, neither of which is the case with a fresh checkout of dojo-boilerplate. So, can you please double check that you actually just clone the dojo-boilerplate repository, run build.sh, and loading index.html in dist fails?
