### ISSUE TITLE
Less clone (recurse submodules) error

### ISSUE THREAD

**Issue by gavreh** [csnover/dojo-boilerplate#64]
When I clone dojo-boilerplate and recurising submodules, it fails on LESS. See attachment.

![less-clone-fail](https://cloud.githubusercontent.com/assets/209355/6026744/d7048d44-aba2-11e4-8512-214b1e5b9756.PNG)

**Comment by csnover** [comment]
It works for me. The error in your output indicates either a transient network error, or you have a corporate firewall that blocks the git protocol. The less.js dependency comes from `dojo/util`, is not a `dojo-boilerplate` dependency, so there’s nothing that I can do from here. It’s not necessary to build apps with dojo-boilerplate (dbp uses Stylus) so you can just ignore it in any case.
